version: "5"

services:
  ntp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ntp-server
    volumes:
      - ./ntp.conf:/etc/ntp.conf  
    ports:
      - "9123:123/udp"  
    restart: always

  conformite-agent:
    build:
      context: .
      dockerfile: Dockerfile-conformite
    container_name: conformite-agent
    volumes:
      - ./agent_conformite.sh:/usr/local/bin/agent_conformite.sh  
    networks:
      conformite-network:
        ipv4_address: 10.0.0.10  
    environment:
      - AGENT_MODE=collect  
    restart: always

  proxy:
    image: haproxy:latest
    container_name: haproxy_proxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8530:8530"
      - "8080:8080"
      - "8053:8053/udp"
    restart: unless-stopped
    networks:
      - conformite-network

networks:
  conformite-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
