version: "5"  
services:
  ntp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ntp-server
    volumes:
      - ./ntp.conf:/etc/ntp.conf  
    ports:
      - "123:123/udp"  
    restart: always
