version: '5'

services:
  ntp-server:
    build: .
    container_name: ntp-server
    ports:
      - "123:123/udp"   
    volumes:
      - ./ntp.conf:/etc/ntp.conf  
    restart: always    
    networks:
      - ntp-network  

networks:
  ntp-network:  
    driver: bridge  
